// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHome.Infrastructure.Data;

#nullable disable

namespace SmartHome.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SmartHomeDbContext))]
    [Migration("20260812141622_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHome.Domain.Device.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartHome.Domain.Device.Models.Device", b =>
                {
                    b.OwnsMany("SmartHome.Domain.Device.Models.Capability", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Options")
                                .HasColumnType("jsonb");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("DeviceId", "Id");

                            b1.ToTable("Capability");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");

                            b1.OwnsOne("SmartHome.Domain.Device.ValueObjects.ValueRange", "Range", b2 =>
                                {
                                    b2.Property<Guid>("CapabilityDeviceId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CapabilityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Max")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Min")
                                        .HasColumnType("integer");

                                    b2.HasKey("CapabilityDeviceId", "CapabilityId");

                                    b2.ToTable("Capability");

                                    b2.WithOwner()
                                        .HasForeignKey("CapabilityDeviceId", "CapabilityId");
                                });

                            b1.Navigation("Range");
                        });

                    b.OwnsOne("SmartHome.Domain.Device.Models.DeviceState", "State", b1 =>
                        {
                            b1.Property<Guid>("DeviceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Values")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("State");

                            b1.HasKey("DeviceId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceId");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("State")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
