// <auto-generated />
using System;
using DeviceSimulator.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeviceSimulator.API.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260805223706_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeviceSimulator.API.Data.DeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DeviceSimulator.API.Data.DeviceEntity", b =>
                {
                    b.OwnsMany("DeviceSimulator.API.Devices.Domain.Models.Capability", "Capabilities", b1 =>
                        {
                            b1.Property<Guid>("DeviceEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("DeviceEntityId", "Id");

                            b1.ToTable("Capability");

                            b1.WithOwner()
                                .HasForeignKey("DeviceEntityId");

                            b1.OwnsOne("DeviceSimulator.API.Devices.Domain.ValueObjects.ValueRange", "Range", b2 =>
                                {
                                    b2.Property<Guid>("CapabilityDeviceEntityId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CapabilityId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Max")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Min")
                                        .HasColumnType("integer");

                                    b2.HasKey("CapabilityDeviceEntityId", "CapabilityId");

                                    b2.ToTable("Capability");

                                    b2.WithOwner()
                                        .HasForeignKey("CapabilityDeviceEntityId", "CapabilityId");
                                });

                            b1.Navigation("Range");
                        });

                    b.OwnsOne("DeviceSimulator.API.Devices.Domain.Models.DeviceState", "State", b1 =>
                        {
                            b1.Property<Guid>("DeviceEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Values")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.HasKey("DeviceEntityId");

                            b1.ToTable("Devices");

                            b1.WithOwner()
                                .HasForeignKey("DeviceEntityId");
                        });

                    b.Navigation("Capabilities");

                    b.Navigation("State")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
